donation form with inputs
CollaborativeEconomics/giving-universe-ui pull request #11
Opened 2023-12-01 02:19 UTC by eliassimpson

2023-12-03 22:07 UTC, JulianKingman commented on components/ui/input.tsx
> +const Switch = React.forwardRef<HTMLDivElement, SwitchProps>(
This can go in its own component

2023-12-03 22:08 UTC, JulianKingman commented on components/ui/input.tsx
> +const InputWithContent = React.forwardRef<
this can also get its own component

2023-12-03 22:09 UTC, JulianKingman commented on components/ui/input.tsx
> +const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
Shad UI has a checkbox component we should use

2023-12-03 22:12 UTC, JulianKingman commented on components/ui/input.tsx
> +const SelectInput = React.forwardRef<HTMLInputElement, SelectInputProps>(
This should get its own component. If you use the `shad` script (`yarn shad`), it should set it up in its own file.

2023-12-03 22:23 UTC, JulianKingman commented on components/ui/input.tsx
> +        <Select
Was the existing Select component too restrictive? (components/ui/select). This is a cool package, but it's pretty big. We'll get a lot of use out of it, mainly curious about the choice.

2023-12-03 22:23 UTC, JulianKingman commented on components/ui/input.tsx
> +function buildOptions(
it would be better to use this as a `useMemo` variable inside the SelectInput component, i.e.
```jsx
const options = useMemo(() => 
  options.map((option) => ({
    ...option,
    symbol: option.symbol || '',
    label: (...etc)
  })
, [options]}
```
The reason being is to control the number of re-renders the Select component does.

2023-12-03 22:24 UTC, JulianKingman commented on components/ui/input.tsx
> +          styles={{
this should also be in a `useMemo` hook (see below)

2023-12-03 22:32 UTC, JulianKingman commented on components/ui/org-stats.tsx
> +  var items = new Array<React.JSX.Element>();
```suggestion
  const items = new Array<React.JSX.Element>();
```

2023-12-03 22:33 UTC, JulianKingman commented on lib/chains/apis.ts
> +export function getChainWallet(chain: string) {
We should make use of this to limit the Select options for the wallet

2023-12-03 22:34 UTC, JulianKingman commented on lib/chains/apis.ts
> +export function getChainWallet(chain: string) {
except this should be `getChainWallets` and should return an array

2023-12-03 22:36 UTC, JulianKingman commented on lib/chains/apis.ts
> +  xlm: { name: 'Lobstr', image: '/xlm-wallet-logo.png' },
so each option here would have an array, for example XLM has Lobstr or Freighter

2023-12-03 22:43 UTC, JulianKingman commented on package.json
> +    "pino-pretty": "^10.2.3",
what's this for?

2023-12-03 22:43 UTC, JulianKingman commented on package.json
> +    "@material-ui/core": "^4.12.4",
What are these for?

2023-12-03 22:44 UTC, JulianKingman commented on package.json
> +    "@material-ui/core": "^4.12.4",
They're quite heavy libraries

2023-12-03 22:44 UTC, JulianKingman commented on public/test.png
😆

2023-12-03 22:45 UTC, JulianKingman commented on components/DonationForm.tsx
> +  const [valueBasis, setValue] = useState(false)
we should probably use react hook form or something, but I'll leave that for another ticket when we connect it up.

2023-12-04 16:40 UTC, eliassimpson commented on package.json
> +    "pino-pretty": "^10.2.3",
i don't know, but after adding imports from `lib/chain` it won't compile without it.

2023-12-04 16:40 UTC, eliassimpson commented on package.json
> +    "@material-ui/core": "^4.12.4",
meant to take those out.

2023-12-04 19:54 UTC, eliassimpson commented on components/ui/input.tsx
> +function buildOptions(
this ended up being done in place within the component. does that work?
```
              <SelectItem
                className="bg-white text-black"
                value={option.value}
                key={option.value}
              >
                <div className="flex flex-row gap-3">
                  <img src={option.image} width="30px" />
                  <div className="my-auto">{option.value}</div>
                </div>
              </SelectItem>
```

2023-12-04 19:57 UTC, eliassimpson commented on lib/chains/apis.ts
> +export function getChainWallet(chain: string) {
how do we know which chains are returned with wallet selection?

2023-12-04 20:25 UTC, eliassimpson commented on lib/chains/apis.ts
> +  xlm: { name: 'Lobstr', image: '/xlm-wallet-logo.png' },
gotcha.

2023-12-05 10:57 UTC, JulianKingman requested changes
Two code suggestions, thanks for all your work on this one, I really appreciate your willingness to refactor things.

2023-12-05 10:57 UTC, JulianKingman commented on package.json
> +    "pino-pretty": "^10.2.3",
looks like walletconnect depends on it and recently removed it... interesting...

2023-12-05 10:57 UTC, JulianKingman commented on lib/chains/apis.ts
> +export function getChainWallet(chain: string) {
Wallets are filtered by chains, not visa-versa. For example xlm can have Lobstr or Freighter (not currently in the code yet). But if you choose bob, only the Metamask wallet will be available. That make any sense?

2023-12-05 10:57 UTC, JulianKingman commented on components/DonationForm.tsx
> +                currentOption={currentWallet}
```suggestion
                currentOption={currentWallet ?? wallets[0]}
```

2023-12-05 10:57 UTC, JulianKingman commented on components/ui/input.tsx
> +function buildOptions(
Yep!

2023-12-05 10:57 UTC, JulianKingman commented on components/ui/checkbox.tsx
> +      </label>
This will allow you to click the label text to check it
```suggestion
      <label className="flex pt-[6px] gap-3 items-center">
        <Checkbox />
        <ModalText text={text} />
      </label>
```

2023-12-06 15:41 UTC, merged