gx-66 initiative page
CollaborativeEconomics/giving-universe-ui pull request #12
Opened 2023-12-07 01:23 UTC by eliassimpson

<img width="1298" alt="Screenshot 2023-12-06 at 7 23 15 PM" src="https://github.com/CollaborativeEconomics/giving-universe-ui/assets/25653090/e857d0c0-e5df-4559-9373-e0fd6f72d342">

2023-12-07 14:55 UTC, kuyawa commented on app/initiatives/[id]/page.tsx
> +  const orgid = props?.params?.id || null
The page being about initiative/id I think we should pass the init id as param and not the org id, why those lines were removed?

Anyway, I'll wait for you to finish so I can connect the database to the page and we don't use dummy data anymore

2023-12-07 14:57 UTC, kuyawa reviewed
Too many changes, hard for me to follow. I'll leave it to Julian to merge

2023-12-07 15:28 UTC, eliassimpson commented on app/initiatives/[id]/page.tsx
> +  const orgid = props?.params?.id || null
good catch. thanks.

a lot of the changes are formatting stuff. it would be nice to do a PR just executing formatting so it's out of the way.

2023-12-14 12:36 UTC, JulianKingman requested changes
Here are a couple design changes, and then in the comments there are some housekeeping things. Thanks, this is looking great!
<img width="1821" alt="Screenshot 2023-12-14 at 9 17 48 AM" src="https://github.com/CollaborativeEconomics/giving-universe-ui/assets/1566400/cdaa03f5-1d18-49c5-9ee1-baa7a804c3d4">

2023-12-14 12:36 UTC, JulianKingman commented on app/initiatives/[id]/page.tsx
> +              <p className="text-3xl font-semibold">Initiatives</p>
```suggestion
              <p className="text-3xl font-semibold">Other Initiatives</p>
```

2023-12-14 12:36 UTC, JulianKingman commented on app/initiatives/[id]/page.tsx
> +                  <InitiativeCardCompact key={Math.random()} data={item} />
it's better to use a key that won't change, for performance. Any string can be used, usually I'll do something like `other-initiative-${initiativeId}`, but as long as it's unique it doesn't matter so much

2023-12-14 12:36 UTC, JulianKingman commented on app/initiatives/[id]/page.tsx
> +                  <InitiativeCardCompact key={Math.random()} data={item} />
Obviously since this is dummy data it doesn't really matter

2023-12-14 12:36 UTC, JulianKingman commented on app/initiatives/page.tsx
> +      <div className="grid grid-flow-row grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-10 pt-10">
nice 👌 , looks better

2023-12-14 12:36 UTC, JulianKingman commented on app/navigation-menu.tsx
> +                <ul className="grid gap-3 p-4 md:w-[400px] xl:w-[500px] xl:grid-cols-[.75fr_1fr]">
don't know what this does, but I'm happy to see you fixing things here and there 👍

2023-12-14 12:36 UTC, JulianKingman commented on app/organizations/[organizationId]/page.tsx
> +        <OrgSocials
👍

2023-12-14 12:36 UTC, JulianKingman commented on app/organizations/[organizationId]/page.tsx
> +                <OrgStats
👍

2023-12-14 12:36 UTC, JulianKingman commented on components/OrganizationAvatar.tsx
> +        <AvatarTitle size={avatarProps?.size} title={name ?? 'no name'} />
we should probably either require `name`, or not render AvatarTitle when it's absent

2023-12-14 12:36 UTC, JulianKingman commented on components/StoryCard.tsx
> +        <OrganizationAvatar name={props.data.name} image={props.data.imgSrc} />
This component has few enough properties that we can pass them directly, i.e. `props.imgSrc` instead of `props.data.imgSrc`

2023-12-14 12:36 UTC, JulianKingman commented on components/initiativeCard.tsx
> +          orgStatProps={{
same here, we can pass `amountRaised`, `amountTarget` etc directly as props

2023-12-14 12:36 UTC, JulianKingman commented on components/initiativeCardCompact.tsx
> +            src={props.data.imgSrc}
and here (`props.imgSrc`)

2023-12-14 12:36 UTC, JulianKingman commented on components/ui/NFTReceiptText.tsx
🧹 make an NFTReceipt folder, put this inside and you can rename the NFTReceipt component to index

2023-12-14 12:36 UTC, JulianKingman commented on tailwind.config.ts
> +      xxl: '1440px',
nice

2023-12-14 14:04 UTC, eliassimpson commented on components/OrganizationAvatar.tsx
> +        <AvatarTitle size={avatarProps?.size} title={name ?? 'no name'} />
name is required, but it could be empty string. i think for now it's useful to be able to see a placeholder (since we're dealing with a lot of dev data that might not be fully filled).

2023-12-14 14:21 UTC, eliassimpson commented on app/navigation-menu.tsx
> +                <ul className="grid gap-3 p-4 md:w-[400px] xl:w-[500px] xl:grid-cols-[.75fr_1fr]">
this shouldn't change anything, just adapting to the scaled screen sizes in tailwind config.

2023-12-14 14:35 UTC, eliassimpson commented on components/initiativeCard.tsx
> +          orgStatProps={{
`orgStatProps` is bundled because the shad component has helper functions to build the list elements from the stats. though it makes sense to define them individually for the component in a one-off, it's a lot of parameters to be fire-chaining to multiple functions.
`function buildList(props: OrgStatsProps): Array<React.JSX.Element>`

2023-12-14 23:17 UTC, JulianKingman approved these changes
It's 99% there, so I'm going to approve, b/c it will be easier to make the changes than describe them and go back and forth 😆 

I'll have a PR for you to review shortly :)

2023-12-14 23:38 UTC, merged