Kuyawa merge
CollaborativeEconomics/giving-universe-ui pull request #40
Opened 2024-04-10 21:21 UTC by kuyawa

Finished first round of big dev merge

2024-04-11 01:24 UTC, JulianKingman requested changes
Looking really good George! Couple changes.

2024-04-11 01:24 UTC, JulianKingman commented on lib/utils/api.ts
> +export async function addAnonymousUser(address:string, chain:string){
This looks like a duplicate function (I see an anonymous.tsx file)

2024-04-11 01:24 UTC, JulianKingman commented on lib/utils/api.ts
> +  const result = await postApi('session', rec)
What does the session API do? I should probably know this, but it's my first time noticing

2024-04-11 01:24 UTC, JulianKingman commented on lib/utils/receipt.tsx
> +export default async function sendReceipt(data:any){
we should rename the other `sendReceipt` function to `sendEmailReceipt`

2024-04-11 01:24 UTC, JulianKingman commented on package.json
> +    "react-toastify": "^10.0.5",
we can get rid of this

2024-04-11 01:24 UTC, JulianKingman commented on package.json
> +    "clipboard-copy": "^4.0.1",
do we need this, or can we use native web clipboard functions? i.e.
```
await navigator.clipboard.writeText(text);
await navigator.clipboard.readText();
```

2024-04-11 01:24 UTC, JulianKingman commented on package-lock.json
delete, use yarn

2024-04-11 21:21 UTC, kuyawa commented on app/api/route.tsx
> +async function testOrganizations():Promise<Organization[]> {
Just testing, will remove them

2024-04-11 21:23 UTC, kuyawa commented on app/initiatives/[id]/page.tsx
> +            {stories?.length &&
Tell that to the smart bunny

2024-04-11 21:28 UTC, kuyawa commented on app/profile/[userId]/page.tsx
> +  const stories:[Story] = await getRecentStories(5) || []
Fixed

2024-04-11 21:31 UTC, kuyawa commented on components/DonationForm.tsx
> +interface IDonation {
No, they're temporary data collected to process the donation and payment functions, they will be part of the donation record later on once we add more data

2024-04-11 21:36 UTC, kuyawa commented on components/DonationFormSelect.tsx
> +                  <Image src={option.image} width={30} height={30} alt="Selected image" onError={(e) => e.currentTarget.style.display = 'none'} />
These changes were suggested by the stupid bunny. To be honest I don't like trapping errors in html but if we don't find the image for any reason we should show a placeholder. So, image should be checked for no empty string but error should be trapped if media storage errors out serving the image

2024-04-11 21:36 UTC, kuyawa commented on components/ShareModal.tsx
> +import { toast, ToastContainer } from 'react-toastify'
Again smart bunny is not that smart. I consider the toast too much for such a small UI, we may show a COPIED text in the button instead

2024-04-11 21:39 UTC, kuyawa commented on components/ui/claim-button.tsx
> +  status: string
You are right, ReceiptStatus should be it

2024-04-11 21:42 UTC, kuyawa commented on lib/chains/client/base.ts
> +      callback({error:ex.message})
Or simply use ex:Error?

2024-04-11 21:46 UTC, kuyawa commented on lib/utils/api.ts
> +export async function addAnonymousUser(address:string, chain:string){
Client and server calls. I'll try to merge them but really don't know how to call registry functions from client except from api

2024-04-11 22:00 UTC, kuyawa commented on lib/utils/api.ts
> +export async function addAnonymousUser(address:string, chain:string){
Ok, merged into one

2024-04-11 22:34 UTC, kuyawa commented on lib/utils/api.ts
> +  const result = await postApi('session', rec)
Relic from the past, will remove it

2024-04-11 22:38 UTC, kuyawa commented on lib/utils/receipt.tsx
> +export default async function sendReceipt(data:any){
We may move this to the api lib as it relates to api calls

2024-04-11 22:43 UTC, kuyawa commented on lib/utils/receipt.tsx
> +export default async function sendReceipt(data:any){
Done as emailReceipt as it's the only thing it does

2024-04-11 22:46 UTC, kuyawa commented on package.json
> +    "clipboard-copy": "^4.0.1",
It was using browser functions before but the clever cottontail suggested to use react libs

2024-04-11 22:49 UTC, kuyawa commented on package.json
> +    "react-toastify": "^10.0.5",
Removed

2024-04-11 22:51 UTC, kuyawa commented on package-lock.json
Done, but I use npm as yarn gives me headaches and bun errors out

2024-04-11 22:56 UTC, kuyawa reviewed
All issues solved

2024-04-12 13:03 UTC, JulianKingman approved these changes
I made one change to the claim-button, have a look how I made the types. I first made ReceiptStatus a strict const (not sure if that's the right word) by doing:
```jsx
const ReceiptStatus = {...} as const;
```
I could then use this to create an enum
```jsx
type ReceiptStatusEnum = (typeof ReceiptStatus)[keyof typeof ReceiptStatus]
```
This gets the values of the statuses from the strict const object

2024-04-15 20:23 UTC, merged